### ISSUE TITLE
Bracket, Concurrent, ConcurrentEffect Variants

### ISSUE THREAD

**Issue by ChristopherDavenport** [ChristopherDavenport/scalaz-task-effect#7]
I am unsure if this has the necessary features to implement the above in a clean manner. As these will likely be released soon. I wanted to make sure the issue was raised where we could discuss how these might be implemented.

**Comment by joroKr21** [comment]
I guess `Bracket` would be needed to upgrade to the latest cats-effect. I will take a stab at this tonight and see how it goes.

**Comment by ChristopherDavenport** [comment]
Take a look at whatever is present in https://github.com/djspiewak/shims/tree/master/effect

Where it needed to be integrated with the rest of the hierarchy.

**Comment by joroKr21** [comment]
Hmm interesting, I didn't know about shims-effect. Looks like it serves the same purpose as this library, but a bit more heavyweight (I think it uses macros as well). But the implementation of `bracketCase` looks exactly like what one would expect.
